//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KDMDB : DbContext
    {
        public KDMDB()
            : base("name=KDMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<tbl_actions> tbl_actions { get; set; }
        public virtual DbSet<tbl_address> tbl_address { get; set; }
        public virtual DbSet<tbl_address_types> tbl_address_types { get; set; }
        public virtual DbSet<tbl_company> tbl_company { get; set; }
        public virtual DbSet<tbl_config> tbl_config { get; set; }
        public virtual DbSet<tbl_contact_person> tbl_contact_person { get; set; }
        public virtual DbSet<tbl_controllers> tbl_controllers { get; set; }
        public virtual DbSet<tbl_country> tbl_country { get; set; }
        public virtual DbSet<tbl_departments> tbl_departments { get; set; }
        public virtual DbSet<tbl_designation> tbl_designation { get; set; }
        public virtual DbSet<tbl_district> tbl_district { get; set; }
        public virtual DbSet<tbl_division> tbl_division { get; set; }
        public virtual DbSet<tbl_employee_status> tbl_employee_status { get; set; }
        public virtual DbSet<tbl_employees> tbl_employees { get; set; }
        public virtual DbSet<tbl_file> tbl_file { get; set; }
        public virtual DbSet<tbl_job_status> tbl_job_status { get; set; }
        public virtual DbSet<tbl_menu_category> tbl_menu_category { get; set; }
        public virtual DbSet<tbl_modules> tbl_modules { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_pay_type> tbl_pay_type { get; set; }
        public virtual DbSet<tbl_phone> tbl_phone { get; set; }
        public virtual DbSet<tbl_phone_types> tbl_phone_types { get; set; }
        public virtual DbSet<tbl_police_station> tbl_police_station { get; set; }
        public virtual DbSet<tbl_RoleActionMappings> tbl_RoleActionMappings { get; set; }
        public virtual DbSet<tbl_RoleActions> tbl_RoleActions { get; set; }
        public virtual DbSet<tbl_training> tbl_training { get; set; }
        public virtual DbSet<tbl_training_status> tbl_training_status { get; set; }
        public virtual DbSet<tbl_user_defaults> tbl_user_defaults { get; set; }
        public virtual DbSet<tbl_user_member_master> tbl_user_member_master { get; set; }
        public virtual DbSet<tbl_user_member_transfer_history> tbl_user_member_transfer_history { get; set; }
        public virtual DbSet<tbl_user_wallet> tbl_user_wallet { get; set; }
        public virtual DbSet<tbl_user_wallet_history> tbl_user_wallet_history { get; set; }
        public virtual DbSet<tbl_dealer_product_stock_history> tbl_dealer_product_stock_history { get; set; }
        public virtual DbSet<tbl_dealer_product_stock_master> tbl_dealer_product_stock_master { get; set; }
        public virtual DbSet<tbl_products_history> tbl_products_history { get; set; }
        public virtual DbSet<tbl_products_quantity_update_history> tbl_products_quantity_update_history { get; set; }
        public virtual DbSet<tbl_kdm_settings_history> tbl_kdm_settings_history { get; set; }
        public virtual DbSet<tbl_product_type> tbl_product_type { get; set; }
        public virtual DbSet<tbl_company_funds_master> tbl_company_funds_master { get; set; }
        public virtual DbSet<tbl_company_funds_history> tbl_company_funds_history { get; set; }
        public virtual DbSet<tbl_member_bonus_master> tbl_member_bonus_master { get; set; }
        public virtual DbSet<tbl_member_bonus_temp> tbl_member_bonus_temp { get; set; }
        public virtual DbSet<tbl_dealer_stockist_commission_master> tbl_dealer_stockist_commission_master { get; set; }
        public virtual DbSet<tbl_dealer_type> tbl_dealer_type { get; set; }
        public virtual DbSet<tbl_dealers> tbl_dealers { get; set; }
        public virtual DbSet<tbl_members> tbl_members { get; set; }
        public virtual DbSet<tbl_thana> tbl_thana { get; set; }
        public virtual DbSet<tbl_union> tbl_union { get; set; }
        public virtual DbSet<tbl_shipping_charge> tbl_shipping_charge { get; set; }
        public virtual DbSet<tbl_member_tree_history> tbl_member_tree_history { get; set; }
        public virtual DbSet<tbl_member_tree> tbl_member_tree { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_notice> tbl_notice { get; set; }
        public virtual DbSet<tbl_file_details> tbl_file_details { get; set; }
        public virtual DbSet<tbl_cus_binary_balance> tbl_cus_binary_balance { get; set; }
        public virtual DbSet<tbl_generation_percentages> tbl_generation_percentages { get; set; }
        public virtual DbSet<tbl_process_to_tmp_account> tbl_process_to_tmp_account { get; set; }
        public virtual DbSet<tbl_process_code> tbl_process_code { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<tbl_transaction> tbl_transaction { get; set; }
        public virtual DbSet<tbl_PvBv_history> tbl_PvBv_history { get; set; }
        public virtual DbSet<tbl_binary_matching_data> tbl_binary_matching_data { get; set; }
        public virtual DbSet<tbl_transaction_password> tbl_transaction_password { get; set; }
        public virtual DbSet<tbl_transaction_purpose_code> tbl_transaction_purpose_code { get; set; }
        public virtual DbSet<tbl_pv_point> tbl_pv_point { get; set; }
        public virtual DbSet<tbl_member_account_data> tbl_member_account_data { get; set; }
        public virtual DbSet<tbl_tax_account_data> tbl_tax_account_data { get; set; }
        public virtual DbSet<tbl_member_leadeship_position> tbl_member_leadeship_position { get; set; }
        public virtual DbSet<tbl_vat_account_data> tbl_vat_account_data { get; set; }
        public virtual DbSet<tbl_kdm_settings_master> tbl_kdm_settings_master { get; set; }
        public virtual DbSet<tbl_products_master> tbl_products_master { get; set; }
        public virtual DbSet<tbl_add_to_cart> tbl_add_to_cart { get; set; }
        public virtual DbSet<tbl_orders> tbl_orders { get; set; }
        public virtual DbSet<tbl_order_Line_item> tbl_order_Line_item { get; set; }
        public virtual DbSet<tbl_product_category> tbl_product_category { get; set; }
        public virtual DbSet<tbl_purchase> tbl_purchase { get; set; }
        public virtual DbSet<tbl_member_bonus_history> tbl_member_bonus_history { get; set; }
    }
}
