//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_wallet
    {
        public string UserId { get; set; }
        public Nullable<decimal> Wallet01 { get; set; }
        public Nullable<decimal> Wallet02 { get; set; }
        public Nullable<decimal> Wallet03 { get; set; }
        public Nullable<decimal> Wallet04 { get; set; }
        public Nullable<decimal> Wallet05 { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string ModificationBy { get; set; }
    }
}
