//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kdm_settings_master
    {
        public long ID { get; set; }
        public decimal WalletBonus { get; set; }
        public long PVForWalletBonus { get; set; }
        public decimal SponsorBonus { get; set; }
        public long PVForSponsorBonus { get; set; }
        public decimal BinaryMatchingBonus { get; set; }
        public long PVForBinaryMatchingBonus { get; set; }
        public Nullable<long> MaxBinaryMatchingCount { get; set; }
        public double GenerationBonus { get; set; }
        public long GenerationBonusLayer { get; set; }
        public decimal MonthlyRoyaltyBonus { get; set; }
        public long PVForMonthlyRoyaltyBonus { get; set; }
        public double PerformanceBonusPercentage { get; set; }
        public double LeadershipBonusPercentage { get; set; }
        public decimal RankIncentiveBonus { get; set; }
        public double RoyalClubBonusPercentage { get; set; }
        public double ECommerceBonusPercentage { get; set; }
        public decimal DealerCommission { get; set; }
        public long PVForDealerCommision { get; set; }
        public decimal StockistCommission { get; set; }
        public long PVForStockistCommision { get; set; }
        public Nullable<long> NextMemberID { get; set; }
        public Nullable<long> NextOrderID { get; set; }
    }
}
