//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_file_details
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string UploadBy { get; set; }
        public string FileNote { get; set; }
    }
}
