//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dealer_stockist_commission_master
    {
        public string DealerID { get; set; }
        public decimal DealerCommission { get; set; }
        public decimal StockistCommission { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
