//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employees
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string CardID { get; set; }
        public string FingerPrintID { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<long> PhotoID { get; set; }
        public string Name { get; set; }
        public string BanglaName { get; set; }
        public string CompanyCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string FathersName { get; set; }
        public string FactoryCode { get; set; }
        public string DeptCode { get; set; }
        public string EmpGrpCode { get; set; }
        public string DesigCode { get; set; }
        public string SubSection { get; set; }
        public string Shift { get; set; }
        public string MothersName { get; set; }
        public string NID { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string MaritialStatus { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public string Nationality { get; set; }
        public int HasChild { get; set; }
        public string ReferenceEmployeeID { get; set; }
        public string ReligionCode { get; set; }
        public bool PFDeduct { get; set; }
        public int Service_length { get; set; }
        public int BasicSalary { get; set; }
        public Nullable<int> GrossSalary { get; set; }
        public int AnyAllowances { get; set; }
        public double HourlyRate { get; set; }
        public int PayTypeCode { get; set; }
        public int EmpJobStatusCode { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<bool> Transport { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public bool OverTime { get; set; }
        public string InputterID { get; set; }
        public string AuthorizerID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public int LastIncYear { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string Grade { get; set; }
        public Nullable<bool> FingerTaken { get; set; }
        public Nullable<int> InputStatus { get; set; }
    }
}
