//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dealer_product_stock_history
    {
        public long ID { get; set; }
        public string DealerID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<int> AddedQuantity { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
