//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_leadeship_position
    {
        public int ID { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> PreMatching { get; set; }
        public Nullable<int> CurMatching { get; set; }
        public Nullable<int> TotalMatching { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Position { get; set; }
    }
}
