//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> ProductTypeID { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> BP { get; set; }
        public Nullable<int> RB { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> TotalPV { get; set; }
        public Nullable<int> TotalBV { get; set; }
        public string DealerID { get; set; }
        public string PaymentAddress { get; set; }
        public string ShipmentAddress { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public string OrderBy { get; set; }
        public string OrderApprovedBy { get; set; }
        public string OrderCanceledBy { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string PaymentType { get; set; }
        public string Remarks { get; set; }
    }
}
