//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_bonus_temp
    {
        public string MemberID { get; set; }
        public decimal WalleBonusBalance { get; set; }
        public decimal SponsorBonusBalance { get; set; }
        public decimal BinaryMatchingBalance { get; set; }
        public decimal GenerationBonusBalance { get; set; }
        public decimal MonthlyRoyalityBonusBalance { get; set; }
        public decimal PerformanceBonusBalance { get; set; }
        public decimal LeadershipBonusBalance { get; set; }
        public decimal RankBonusBalance { get; set; }
        public decimal RoyalClubBonusBalance { get; set; }
        public decimal ECommerceBonusBalance { get; set; }
        public decimal DealerBonusBalance { get; set; }
        public decimal StockistBonusBalance { get; set; }
    }
}
