//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_phone
    {
        public long ID { get; set; }
        public string EmployeeId { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNumber { get; set; }
    }
}
