//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_bonus_master
    {
        public string MemberID { get; set; }
        public decimal WalletBonus { get; set; }
        public decimal SponsorBonus { get; set; }
        public decimal GenerationBonus { get; set; }
        public decimal MonthlyRoyalityBonus { get; set; }
        public decimal PerformanceBonus { get; set; }
        public decimal LeadershipBonus { get; set; }
        public decimal RankIncentive { get; set; }
        public decimal RoyalClubBonus { get; set; }
        public decimal ECommerceBonus { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public decimal BinaryMatchingBonus { get; set; }
    }
}
