//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_shipping_charge
    {
        public int ID { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string Upozila { get; set; }
        public string Area { get; set; }
        public string Weight { get; set; }
        public Nullable<int> ShipCharge { get; set; }
    }
}
