//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company_funds_history
    {
        public System.Guid HistID { get; set; }
        public string FundName { get; set; }
        public decimal FundAmount { get; set; }
        public decimal FundTotalAmount { get; set; }
        public string FundUnitAmount { get; set; }
        public long PVUsed { get; set; }
        public long PVUnit { get; set; }
        public string FundFrom { get; set; }
        public string FundFromID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
