//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_tree
    {
        public int SerialNo { get; set; }
        public string PlacementID { get; set; }
        public string LeftID { get; set; }
        public string RightID { get; set; }
        public string SponsorID { get; set; }
        public Nullable<double> LeftPoint { get; set; }
        public Nullable<double> RightPoint { get; set; }
        public Nullable<double> PV { get; set; }
        public Nullable<double> BV { get; set; }
        public Nullable<bool> IsRoot { get; set; }
        public Nullable<double> TotalBV { get; set; }
        public Nullable<long> LeftChildCount { get; set; }
        public Nullable<long> RightChildCount { get; set; }
    }
}
