//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_bonus_history
    {
        public System.Guid ID { get; set; }
        public string MemberID { get; set; }
        public string FromMemberID { get; set; }
        public string BonusSource { get; set; }
        public Nullable<decimal> PreviousAmount { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
        public decimal BonusTotalAmount { get; set; }
        public decimal BonusLeftPV { get; set; }
        public Nullable<decimal> BonusLeftBV { get; set; }
        public decimal BonusUnitAmount { get; set; }
        public long PVTotal { get; set; }
        public long PVUnit { get; set; }
        public long BVTotal { get; set; }
        public long BVUnit { get; set; }
        public string BonusUnit { get; set; }
        public Nullable<System.DateTime> BonusDate { get; set; }
    }
}
