//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_config
    {
        public long cnfg_id { get; set; }
        public string cnfg_app { get; set; }
        public string cnfg_notification_mail { get; set; }
        public string cnfg_notification_mail_pass { get; set; }
        public string cnfg_app_user_default_pass { get; set; }
        public string cnfg_init_area { get; set; }
        public string cnfg_init_controller { get; set; }
        public string cnfg_init_action { get; set; }
    }
}
