//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transaction_password
    {
        public int ID { get; set; }
        public string MemberID { get; set; }
        public string TransPassword { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ResetStatus { get; set; }
    }
}
