//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_process_code
    {
        public int ID { get; set; }
        public string ProcessNo { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public string ProcessBy { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
    }
}
