//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoleActionMappings
    {
        public long ID { get; set; }
        public Nullable<long> Category { get; set; }
        public Nullable<long> Parent { get; set; }
        public string Role { get; set; }
        public string Area { get; set; }
        public string AreaDisplayText { get; set; }
        public string Controller { get; set; }
        public string ControllerDisplayText { get; set; }
        public string Action { get; set; }
        public string ActionDisplayText { get; set; }
        public string Parameters { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ItemOrder { get; set; }
    }
}
