//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PvBv_history
    {
        public int ID { get; set; }
        public string MemberID { get; set; }
        public string ProcessCode { get; set; }
        public Nullable<decimal> PVPoint { get; set; }
        public Nullable<decimal> BVPoint { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
    }
}
