//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_defaults
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string RoleDefault { get; set; }
        public string ModuleDefault { get; set; }
        public string ControllDefault { get; set; }
        public string ActionDefault { get; set; }
    }
}
