//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_members
    {
        public long ID { get; set; }
        public string MemberID { get; set; }
        public string PlacementID { get; set; }
        public string SponsorID { get; set; }
        public string SponsorName { get; set; }
        public Nullable<int> Position { get; set; }
        public string DistributorName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string NID { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string NomineeName { get; set; }
        public string RelationWithNominee { get; set; }
        public string NomineeNIDOrBirthCertificate { get; set; }
        public Nullable<long> PhotoID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
