//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_process_to_tmp_account
    {
        public int ID { get; set; }
        public string MemberID { get; set; }
        public Nullable<decimal> BinaryBalance { get; set; }
        public Nullable<decimal> GeneBalance { get; set; }
        public string ProcessCode { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessBy { get; set; }
        public string InputerID { get; set; }
        public string AuthorizerID { get; set; }
    }
}
