//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_address
    {
        public long ID { get; set; }
        public string EmployeeId { get; set; }
        public string AddressType { get; set; }
        public string Division { get; set; }
        public string City { get; set; }
        public string StreetNo { get; set; }
        public string District { get; set; }
        public string PoliceStation { get; set; }
        public string PostOffice { get; set; }
        public string PostCode { get; set; }
        public string House_ { get; set; }
        public string Country { get; set; }
    }
}
