//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_member_master
    {
        public long ID { get; set; }
        public string UserId { get; set; }
        public string MemberId { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
