//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company_funds_master
    {
        public long ID { get; set; }
        public string FundName { get; set; }
        public decimal FundAmount { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
