//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notice
    {
        public int ID { get; set; }
        public string NoticeNo { get; set; }
        public string NoticePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> NoticeStart { get; set; }
        public Nullable<System.DateTime> NoticeEnd { get; set; }
        public string NoticeType { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> NoticeStatus { get; set; }
    }
}
