//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_wallet_history
    {
        public int TrID { get; set; }
        public string UserId { get; set; }
        public string WalletName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TrType { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string TrBy { get; set; }
    }
}
