//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_designation
    {
        public int ID { get; set; }
        public string DesigCode { get; set; }
        public string DesigName { get; set; }
        public string DesigNameBN { get; set; }
        public int AttnBonus { get; set; }
        public string EmgGroup { get; set; }
        public Nullable<int> holiday_allowance { get; set; }
        public string DeptGrade { get; set; }
        public string EmpType { get; set; }
        public Nullable<int> TiifinAllowance { get; set; }
    }
}
