//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_file
    {
        public long file_id { get; set; }
        public string file_title { get; set; }
        public string file_type { get; set; }
        public string file_details { get; set; }
        public string file_url { get; set; }
        public Nullable<long> file_ref_id { get; set; }
        public string file_ref_type { get; set; }
        public string file_user_by { get; set; }
    }
}
